Repository reactor/.github, pull requests merged in 2024-03, with the labels that each got.

#27 Fix issue template labels
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation_issue.md
  .github/ISSUE_TEMPLATE/enhancement---suggestion.md
Labels: type/enhancement

#28 Add support timeline, remove active development section
  SUPPORT.adoc
Labels: type/documentation, for/team-attention

#29 Add note about release cadence
  SUPPORT.adoc
Labels: type/documentation
